services:
  webapp:
    build:
      dockerfile: Dockerfile
      target: production
    depends_on:
      - db
    environment:
      DB_PASSWORD: service
      DB_USER: service
      DB_NAME: webdev
      DB_HOST: db
      DB_PORT: 7432
    ports:
      - 18080:8080

  db:
    # See config from https://github.com/peterldowns/pgtestdb
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: service
      POSTGRES_PASSWORD: service
      POSTGRES_DB: webdev
    volumes:
      # Uses a tmpfs volume to make tests extremely fast. The data in test
      # databases is not persisted across restarts, nor does it need to be.
      - type: tmpfs
        target: /var/lib/postgresql/data/
    ports:
      - 7432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d webdev" ]
      interval: 30s
      timeout: 10s
      retries: 5
    command:
      - "postgres"
      - "-c" # turn off fsync for speed
      - "fsync=off"
      - "-c" # log everything for debugging
      - "log_statement=all"
